# Generated by Django 5.0.14 on 2026-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobseekers_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='raw_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
