# Generated by Django 5.0.14 on 2026-05-20 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_jobs_raw_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applications',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job', to='users.jobs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job_seeker', to='users.jobseekers'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CANDIDATE', 'Candidate'), ('COMPANY', 'Company'), ('RECRUITER', 'Recruiter')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['account_type'], name='users_account_e502f1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['posted_at'], name='jobs_posted__275cdb_idx'),
        ),
    ]
