# Generated by Django 5.0.14 on 2026-05-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailverificationotp_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='savedjobs',
            unique_together={('job_seeker', 'job')},
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['job_seeker', 'status'], name='application_job_see_a1083a_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['-applied_at'], name='application_applied_f50165_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjobs',
            index=models.Index(fields=['job_seeker', 'job'], name='saved_jobs_job_see_ea194e_idx'),
        ),
    ]
