# Generated by Django 5.0.14 on 2026-05-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_emailverificationotp_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_recruiter', to='users.recruiters'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_job', to='users.jobs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('PLACED', 'Placed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='threadparticipants',
            unique_together={('thread', 'user')},
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['thread', 'sent_at'], name='messages_thread__f33aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['thread', 'is_read'], name='messages_thread__1ab240_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipants',
            index=models.Index(fields=['user'], name='thread_part_user_id_512460_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipants',
            index=models.Index(fields=['thread'], name='thread_part_thread__ad1d30_idx'),
        ),
    ]
