# Generated by Django 5.0.14 on 2026-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_applications_recruiter_alter_applications_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekers',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='open_to_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='open_to_relocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='preferred_company_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='privacy_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
