# Generated by Django 5.0.14 on 2026-06-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_adbudgettransactions_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
