# Generated by Django 5.0.14 on 2026-06-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companies_cin_number_companies_gstin_number'),
        ('users', '0012_alter_customuser_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_company', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('HIRING_MANAGER', 'Hiring Manager'), ('INTERVIEWER', 'Interviewer'), ('VIEWER', 'Viewer')], max_length=50, null=True),
        ),
    ]
