# Generated by Django 5.0.14 on 2026-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_supportreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
