/**
 * Icon.tsx — Centralized icon lookup component
 *
 * Maps Material Symbols Outlined string names → lucide-react SVG components.
 * Use this for Pattern B (dynamic) icons where the icon name comes from data arrays.
 *
 * Usage:
 *   <Icon name="dashboard" size={20} className="text-primary" />
 */

import React from "react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignJustify,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BellOff,
  BellRing,
  Bookmark,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Clock,
  Code2,
  Coins,
  Columns3,
  Compass,
  CreditCard,
  Crown,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FilePen,
  FileUp,
  FileUser,
  Folder,
  FolderOpen,
  Globe,
  GlobeLock,
  GraduationCap,
  GripVertical,
  Heart,
  Headphones,
  HelpCircle,
  Home,
  IdCard,
  Info,
  Languages,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Monitor,
  Moon,
  Network,
  Palette,
  Pencil,
  Plus,
  PlusCircle,
  Printer,
  RefreshCw,
  Rocket,
  Rss,
  Save,
  ScrollText,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Users,
  User,
  UserCircle,
  UserPlus,
  Video,
  WifiOff,
  X,
  Zap,
  Inbox,
  Table,
  type LucideIcon,
} from "lucide-react";

/** Map of all Material Symbol icon names used in this codebase → Lucide components */
const iconMap: Record<string, LucideIcon> = {
  account_circle: UserCircle,
  add: Plus,
  add_a_photo: Camera,
  add_circle: PlusCircle,
  admin_panel_settings: ShieldAlert,
  alternate_email: AtSign,
  analytics: BarChart3,
  architecture: Compass,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_drop_down: ChevronDown,
  auto_awesome: Sparkles,
  badge: IdCard,
  bolt: Zap,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  business: Building2,
  business_center: Briefcase,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  camera_alt: Camera,
  category: Layers,
  chat: MessageSquare,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  code: Code2,
  contact_page: FileUser,
  corporate_fare: Building,
  credit_card: CreditCard,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  devices: Monitor,
  domain: Globe,
  domain_disabled: GlobeLock,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_document: FilePen,
  error: AlertCircle,
  error_outline: AlertCircle,
  event: CalendarDays,
  event_upcoming: CalendarClock,
  expand_more: ChevronDown,
  explore: Compass,
  facebook: Share2, // lucide-react no longer exports Facebook; Share2 is a reasonable fallback
  fact_check: ClipboardCheck,
  favorite: Heart,
  folder: Folder,
  folder_open: FolderOpen,
  format_list_bulleted: List,
  forum: MessagesSquare,
  group: Users,
  groups: Users,
  help: HelpCircle,
  history_edu: ScrollText,
  home: Home,
  hub: Network,
  info: Info,
  insights: TrendingUp,
  language: Languages,
  light_mode: Sun,
  link: Link,
  list: List,
  location_on: MapPin,
  lock: Lock,
  lock_reset: Lock,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  menu_book: BookOpen,
  model_training: BrainCircuit,
  monitoring: Activity,
  notifications: Bell,
  notifications_active: BellRing,
  notifications_off: BellOff,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  phone_iphone: Smartphone,
  photo_camera: Camera,
  pin_drop: MapPin,
  print: Printer,
  progress_activity: Loader2,
  psychology: Brain,
  public: Globe,
  query_stats: BarChart3,
  radio_button_checked: CheckCircle2,
  reorder: AlignJustify,
  rocket_launch: Rocket,
  rss_feed: Rss,
  save: Save,
  schedule: Clock,
  school: GraduationCap,
  school_off: GraduationCap,
  search: Search,
  search_check: SearchCheck,
  search_off: SearchX,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shopping_cart: ShoppingCart,
  sms: MessageSquare,
  south: ArrowDown,
  star: Star,
  stars: Sparkles,
  support_agent: Headphones,
  sync: RefreshCw,
  terminal: Terminal,
  thumb_up: ThumbsUp,
  timer: Timer,
  tips_and_updates: Lightbulb,
  token: Coins,
  track_changes: Target,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  unfold_more: SlidersHorizontal,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  video_call: Video,
  view_week: Columns3,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: AlertTriangle,
  wifi_off: WifiOff,
  work: Briefcase,
  work_history: BriefcaseBusiness,
  work_outline: Briefcase,
  work_off: Briefcase,
  workspace_premium: Crown,
  inbox: Inbox,
  grid_on: Table,
};


export type IconProps = {
  /** Material Symbol name (e.g. "dashboard", "search") */
  name: string;
  /** Icon size in px. Default: 20 */
  size?: number;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
  strokeWidth?: number;
};

/**
 * Renders a Lucide SVG icon by Material Symbol name.
 * Falls back to a neutral placeholder if the name is unmapped.
 */
export default function Icon({
  name,
  size = 20,
  className = "",
  "aria-hidden": ariaHidden = true,
  strokeWidth = 2,
}: IconProps) {
  const LucideComponent = iconMap[name];

  if (!LucideComponent) {
    // Soft fallback: renders an empty square placeholder with a console warning
    if (process.env.NODE_ENV === "development") {
      console.warn(`[Icon] Unmapped icon name: "${name}". Add it to Icon.tsx iconMap.`);
    }
    return (
      <span
        aria-hidden={ariaHidden}
        className={`inline-block opacity-0 ${className}`}
        style={{ width: size, height: size }}
      />
    );
  }

  return (
    <LucideComponent
      size={size}
      className={className}
      aria-hidden={ariaHidden}
      strokeWidth={strokeWidth}
    />
  );
}
