# Generated by Django 5.0.14 on 2026-06-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AddField(
            model_name='candidateshortlists',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_shortlists_job', to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='candidateshortlists',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_shortlists_recruiter', to='companies.recruiters'),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobalerts',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidateshortlists',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_shortlists_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidateprojects',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_projects_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidateportfoliolinks',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_portfolio_links_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidatelanguages',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_languages_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experience_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_education_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='candidatecertifications',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_certifications_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='jobseekerskills',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_skills_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddField(
            model_name='jobseekerskills',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_skills_skill', to='taxonomy.skills'),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs_job', to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs_job_seeker', to='candidates.jobseekers'),
        ),
        migrations.AddIndex(
            model_name='savedjobs',
            index=models.Index(fields=['job_seeker', 'job'], name='saved_jobs_job_see_ea194e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjobs',
            unique_together={('job_seeker', 'job')},
        ),
            ],
            database_operations=[]
        )
    ]
