# Generated by Django 5.0.14 on 2026-06-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
        ('companies', '0005_alter_recruiters_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateshortlists',
            unique_together={('recruiter', 'job_seeker')},
        ),
    ]
