# Generated by Django 5.0.14 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidateshortlists_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekers',
            name='is_open_to_opportunities',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
