# Generated by Django 5.0.14 on 2026-06-24 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_jobseekers_is_open_to_opportunities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfileViews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='candidates.jobseekers')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profile_views',
                'indexes': [models.Index(fields=['job_seeker', 'viewed_at'], name='candidate_p_job_see_aea9ee_idx')],
            },
        ),
    ]
