# Generated by Django 5.0.14 on 2026-06-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_add_candidate_profile_views'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobseekerskills',
            unique_together={('job_seeker', 'skill')},
        ),
    ]
