# Generated by Django 5.0.14 on 2026-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_jobseekerskills_unique_together'),
        ('companies', '0007_companies_additional_locations_and_more'),
        ('jobs', '0003_alter_jobskills_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofileviews',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_company', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='candidateprofileviews',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_views_job', to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='candidateprofileviews',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='profile_view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
