# Generated by Django 5.0.14 on 2026-06-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AddField(
            model_name='advertiseraccounts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_accounts_company', to='companies.companies'),
        ),
        migrations.AddField(
            model_name='advertiseraccounts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_accounts_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcampaigns',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns_advertiser', to='commerce.advertiseraccounts'),
        ),
        migrations.AddField(
            model_name='creditbalances',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_balances_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditreservations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_reservations_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransactions',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions_credit_type', to='commerce.credittypes'),
        ),
        migrations.AddField(
            model_name='creditreservations',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_reservations_credit_type', to='commerce.credittypes'),
        ),
        migrations.AddField(
            model_name='creditpackages',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_packages_credit_type', to='commerce.credittypes'),
        ),
        migrations.AddField(
            model_name='creditbalances',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_balances_credit_type', to='commerce.credittypes'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_order', to='commerce.orders'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_order', to='commerce.orders'),
        ),
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_order', to='commerce.orders'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_product', to='commerce.products'),
        ),
        migrations.AddField(
            model_name='creditpackages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_packages_product', to='commerce.products'),
        ),
        migrations.AddField(
            model_name='refunds',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_payment', to='commerce.payments'),
        ),
        migrations.AddField(
            model_name='revenuedistributions',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distributions_order_item', to='commerce.orderitems'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_plan', to='commerce.subscriptionplans'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage_subscription', to='commerce.subscriptions'),
        ),
        migrations.AddField(
            model_name='wallets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertiseraccounts',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_accounts_wallet', to='commerce.wallets'),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions_wallet', to='commerce.wallets'),
        ),
        migrations.AddField(
            model_name='adbudgettransactions',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_budget_transactions_wallet_transaction', to='commerce.wallettransactions'),
        ),
            ],
            database_operations=[]
        )
    ]
