# Generated by Django 5.0.14 on 2026-06-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaignmetrics',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adcampaigns',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='adconversions',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adcreatives',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adclicks',
            name='creative',
        ),
        migrations.RemoveField(
            model_name='adclicks',
            name='impression',
        ),
        migrations.RemoveField(
            model_name='adclicks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adconversions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adimpressions',
            name='creative',
        ),
        migrations.RemoveField(
            model_name='adimpressions',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='adimpressions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advertiseraccounts',
            name='company',
        ),
        migrations.RemoveField(
            model_name='advertiseraccounts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advertiseraccounts',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='AdBudgetTransactions',
        ),
        migrations.DeleteModel(
            name='AdCampaignMetrics',
        ),
        migrations.DeleteModel(
            name='AdCampaigns',
        ),
        migrations.DeleteModel(
            name='AdClicks',
        ),
        migrations.DeleteModel(
            name='AdConversions',
        ),
        migrations.DeleteModel(
            name='AdCreatives',
        ),
        migrations.DeleteModel(
            name='AdSlots',
        ),
        migrations.DeleteModel(
            name='AdImpressions',
        ),
        migrations.DeleteModel(
            name='AdvertiserAccounts',
        ),
    ]
