# Generated by Django 5.0.14 on 2026-06-03 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_remove_adbudgettransactions_campaign_and_more'),
        ('candidates', '0001_initial'),
        ('companies', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('PLACED', 'Placed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('interview_schedule', models.DateTimeField(blank=True, null=True)),
                ('offer_details', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job_seeker', to='candidates.jobseekers')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_recruiter', to='companies.recruiters')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('recruiter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_notes_recruiter_user', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_notes_application', to='jobs.applications')),
            ],
            options={
                'db_table': 'application_notes',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=255, null=True)),
                ('new_status', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_status_history_application', to='jobs.applications')),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_status_history_changed_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_status_history',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('raw_location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=50, null=True)),
                ('experience_required', models.IntegerField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('boost_score', models.IntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_company', to='companies.companies')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_industry', to='taxonomy.industries')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_job_category', to='taxonomy.jobcategories')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_location', to='taxonomy.locations')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_recruiter', to='companies.recruiters')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_job', to='jobs.jobs'),
        ),
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_skills_job', to='jobs.jobs')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_skills_skill', to='taxonomy.skills')),
            ],
            options={
                'db_table': 'job_skills',
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=255, null=True)),
                ('new_status', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_status_history_changed_by_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_status_history_job', to='jobs.jobs')),
            ],
            options={
                'db_table': 'job_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['posted_at'], name='jobs_posted__275cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['job_seeker', 'status'], name='application_job_see_a1083a_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='applications',
            index=models.Index(fields=['-applied_at'], name='application_applied_f50165_idx'),
        ),
            ],
            database_operations=[]
        )
    ]
