# Generated by Django 5.0.14 on 2026-06-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidateshortlists_unique_together'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('job', 'job_seeker')},
        ),
    ]
