# Generated by Django 5.0.14 on 2026-06-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_applications_unique_together'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobskills',
            unique_together={('job', 'skill')},
        ),
    ]
