# Generated by Django 5.0.14 on 2026-06-03 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_remove_adbudgettransactions_campaign_and_more'),
        ('candidates', '0001_initial'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_badge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='RecruiterPipelines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'recruiter_pipelines',
            },
        ),
        migrations.CreateModel(
            name='CompanyReviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews_company', to='companies.companies')),
                ('job_seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews_job_seeker', to='candidates.jobseekers')),
            ],
            options={
                'db_table': 'company_reviews',
            },
        ),
        migrations.CreateModel(
            name='CompanyTeamInvitations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_team_invitations_company', to='companies.companies')),
            ],
            options={
                'db_table': 'company_team_invitations',
            },
        ),
        migrations.CreateModel(
            name='PipelineStages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages_pipeline', to='companies.recruiterpipelines')),
            ],
            options={
                'db_table': 'pipeline_stages',
            },
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters_subscription_plan', to='commerce.subscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiters',
            },
        ),
        migrations.AddField(
            model_name='recruiterpipelines',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_pipelines_recruiter', to='companies.recruiters'),
        ),
        migrations.CreateModel(
            name='RecruiterSavedSearches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_criteria', models.JSONField(blank=True, null=True)),
                ('alert_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_saved_searches_recruiter', to='companies.recruiters')),
            ],
            options={
                'db_table': 'recruiter_saved_searches',
            },
        ),
            ],
            database_operations=[]
        )
    ]
