# Generated by Django 5.0.14 on 2026-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='cin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='gstin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
