# Generated by Django 5.0.14 on 2026-06-08 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companies_cin_number_companies_gstin_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAuditLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('credits_deducted', models.IntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='CompanyRecruiterRelations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_relations', to='companies.companies')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_relations', to='companies.recruiters')),
            ],
            options={
                'db_table': 'company_recruiter_relations',
                'unique_together': {('company', 'recruiter')},
            },
        ),
    ]
