# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_creditauditlogs_companyrecruiterrelations'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
