# Generated by Django 5.0.14 on 2026-06-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_recruiters_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyteaminvitations',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
