# Generated by Django 5.0.14 on 2026-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyteaminvitations_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='additional_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companies',
            name='address_proof_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='allow_candidate_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='authorized_contact_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='authorized_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_type',
            field=models.CharField(choices=[('private_ltd', 'Private Limited'), ('llp', 'Limited Liability Partnership'), ('proprietorship', 'Proprietorship'), ('public_ltd', 'Public Limited'), ('ngo', 'Non-Governmental Organization'), ('government', 'Government'), ('other', 'Other')], default='private_ltd', max_length=50),
        ),
        migrations.AddField(
            model_name='companies',
            name='culture_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companies',
            name='headquarters_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='hiring_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='hiring_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companies',
            name='id_proof_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='incorporation_doc_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='perks_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companies',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='profile_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='registered_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companies',
            name='tagline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='tax_doc_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='companies',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
